version: '3'
services:
    web:
        build: .
        ports:
            - '5000:5000'
        depends_on:
            - postgres
    postgres:
        image: postgres:13
        ports:
            - '5432:5432'
        restart: always
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
